(lang dune 3.19)

(name shift-reduce)

(generate_opam_files true)

(package
 (name shift-reduce)
 (depends ocaml dune menhir))

(using menhir 3.0)

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
